services:
  verdantgolem:
    # Make sure to change the tag to the version you want to use.
    # https://github.com/VerdantGolemMC/VerdantGolem/pkgs/container/verdantgolem/versions?filters%5Bversion_type%5D=tagged
    #image: ghcr.io/verdantgolemmc/verdantgolem:master
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./data:/verdantgolem
      # Use the following, if you want to make your config immutable
      #- ./config:/verdantgolem/config:ro
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    read_only: true
